#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["httpx>=0.28"]
# ///
"""Generate Swift Codable structs from the backend's FastAPI OpenAPI spec.

Output: ``PalkieTalkie/Generated/APITypes.swift`` — one struct per Pydantic component schema.
Naming: keeps the backend's PascalCase ComponentName; ``snake_case`` fields become camelCase with explicit CodingKeys.

Run after changing a backend router; the pre-commit hook re-runs this and fails on drift.
Override the source with ``--url`` (default ``http://localhost:8000/openapi.json``).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

import httpx

SWIFT_HEADER = """// AUTO-GENERATED by scripts/generate_api_types.py from backend's /openapi.json.
// Do NOT hand-edit — re-run the script.

import Foundation
"""


def snake_to_camel(name: str) -> str:
    parts = name.split("_")
    return parts[0] + "".join(p.title() for p in parts[1:])


def sanitize_struct_name(name: str) -> str:
    # OpenAPI generates names like `PersonaOut`, `Body_record_event_events_post`, etc. Keep PascalCase, drop non-alnum.
    return re.sub(r"[^0-9A-Za-z]", "_", name)


def python_to_swift(prop: dict[str, Any], required: bool) -> str:
    """Map an OpenAPI property dict to a Swift type expression."""
    if "anyOf" in prop:
        types = [t for t in prop["anyOf"] if t.get("type") != "null"]
        if len(types) == 1:
            inner = python_to_swift(types[0], True)
            return inner if required else inner + "?"
        # Fallback for multi-variant unions — surface as String for now and refine when needed.
        return "String?" if not required else "String"
    if "$ref" in prop:
        ref_name = prop["$ref"].rsplit("/", 1)[-1]
        return sanitize_struct_name(ref_name) + ("" if required else "?")
    schema_type = prop.get("type")
    fmt = prop.get("format")
    if schema_type == "string":
        base = "String"
        if fmt == "date-time":
            base = "Date"
        elif fmt == "uuid":
            base = "UUID"
    elif schema_type == "integer":
        base = "Int"
    elif schema_type == "number":
        base = "Double"
    elif schema_type == "boolean":
        base = "Bool"
    elif schema_type == "array":
        item_type = python_to_swift(prop.get("items", {}), True)
        base = f"[{item_type}]"
    elif schema_type == "object":
        # Free-form dicts — model as [String: String] until we need richer.
        base = "[String: String]"
    else:
        base = "String"
    return base if required else base + "?"


def emit_struct(name: str, schema: dict[str, Any]) -> list[str]:
    props: dict[str, Any] = schema.get("properties", {})
    required: set[str] = set(schema.get("required", []))
    lines = [f"public struct {name}: Codable, Sendable {{"]
    coding_keys: list[tuple[str, str]] = []
    for raw_name, prop in props.items():
        swift_name = snake_to_camel(raw_name)
        swift_type = python_to_swift(prop, raw_name in required)
        lines.append(f"    public let {swift_name}: {swift_type}")
        if swift_name != raw_name:
            coding_keys.append((swift_name, raw_name))
    if coding_keys:
        lines.append("")
        lines.append("    enum CodingKeys: String, CodingKey {")
        for swift_name, raw_name in coding_keys:
            lines.append(f'        case {swift_name} = "{raw_name}"')
        lines.append("    }")
    lines.append("}")
    return lines


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--url",
        default="http://localhost:8000/openapi.json",
        help="Backend OpenAPI URL (default: %(default)s)",
    )
    parser.add_argument(
        "--out",
        default="PalkieTalkie/Generated/APITypes.swift",
        help="Output Swift file path (default: %(default)s)",
    )
    args = parser.parse_args()

    try:
        resp = httpx.get(args.url, timeout=5.0)
        resp.raise_for_status()
    except httpx.HTTPError as exc:
        print(f"[generate_api_types] cannot reach {args.url}: {exc}", file=sys.stderr)
        print(
            "[generate_api_types] start the backend with: "
            "cd ../backend && uvicorn app.main:app --reload --port 8000",
            file=sys.stderr,
        )
        return 1

    spec = resp.json()
    schemas: dict[str, Any] = spec.get("components", {}).get("schemas", {})
    body: list[str] = [SWIFT_HEADER]
    for raw_name, schema in sorted(schemas.items()):
        if schema.get("type") != "object":
            continue
        body.append("")
        body.extend(emit_struct(sanitize_struct_name(raw_name), schema))

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(body) + "\n")
    print(f"[generate_api_types] wrote {out_path} ({len(schemas)} schemas)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
