// AUTO-GENERATED by backend/scripts/iap/generate_swift_constants.py
// Source of truth: backend/app/iap/subscriptions_list.py
// DO NOT EDIT BY HAND — regenerate via boot.sh or `uv run scripts/iap/generate_swift_constants.py`.

import Foundation

enum SubscriptionTier: String, CaseIterable, Identifiable {
    case family
    case individual

    var id: String {
        rawValue
    }
}

enum SubscriptionCycle: String, CaseIterable, Identifiable {
    case monthly
    case yearly

    var id: String {
        rawValue
    }
}

struct SubscriptionID: Hashable, Identifiable {
    let tier: SubscriptionTier
    let cycle: SubscriptionCycle

    var rawValue: String {
        "com.palkietalkie.\(tier.rawValue).\(cycle.rawValue)"
    }

    var id: String {
        rawValue
    }

    static let all: [SubscriptionID] = [
        SubscriptionID(tier: .individual, cycle: .monthly),
        SubscriptionID(tier: .individual, cycle: .yearly),
        SubscriptionID(tier: .family, cycle: .monthly),
        SubscriptionID(tier: .family, cycle: .yearly),
    ]

    static let allRawIDs: Set<String> = Set(all.map(\.rawValue))

    init(tier: SubscriptionTier, cycle: SubscriptionCycle) {
        self.tier = tier
        self.cycle = cycle
    }

    init?(rawValue: String) {
        let parts = rawValue.split(separator: ".")
        guard parts.count == 4,
              parts[0] == "com",
              parts[1] == "palkietalkie",
              let tier = SubscriptionTier(rawValue: String(parts[2])),
              let cycle = SubscriptionCycle(rawValue: String(parts[3]))
        else { return nil }
        self.tier = tier
        self.cycle = cycle
    }
}
